In [1]:
rm(list = ls()); gc()
setwd('/public/workspace/xiapeng/monoRNA/5Artical_new/260316ClinicValidation/gene/UploadGithub/')
library(dplyr)
library(caret)

       used    (Mb) gc trigger (Mb) max used (Mb)
Ncells  631156 33.8 1410617    75.4  989618  52.9
Vcells 1168646  9.0 8388608    64.0 1816498  13.9

Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union


Loading required package: ggplot2

Loading required package: lattice

#### 1. Load Model & test data；

In [2]:
load('./model.GLMnet.mod.21.RData')
class(model.GLMnet.mod)

[1] "list"

In [3]:
load('./test.ifo&exp.RData')
ls()

[1] "model.GLMnet.mod" "test.exp"         "test.ifo"

In [4]:
head(test.ifo)

         Group  score
50122R14 Glioma 0.7564621
50124R5  Glioma 0.9349877
51011R3  NBD    0.1498371
60105R10 NBD    0.1009254

In [5]:
head(test.exp)

         50122R14    50124R5      51011R3   60105R10
A1BG     0.159363088 0.0783735154 0.1237066 0.10714898
A1BG-AS1 0.305959905 0.3710390474 0.5092488 0.41292908
A1CF     0.000000000 0.0008623119 0.0000000 0.00000000
A2M      0.085649355 0.0452480093 0.1126885 0.14051594
A2M-AS1  0.275672195 0.2861197543 0.3968237 0.60649832
A2ML1    0.008933126 0.0172335959 0.0000000 0.00537702

#### 2. Calculate the risk score using the model；

In [6]:
### valid.pred
model.GLMnet.valid.pred <- lapply(model.GLMnet.mod, function(x){
  Prediction.Probs <- predict(x, newdata = t(test.exp[colnames(x$trainingData)[-ncol(x$trainingData)],]), type = "prob") %>% data.frame
  Prediction.Probs = cbind(test.ifo, Prediction.Probs)
  
})

In [7]:
##
model.GLMnet.valid.pred.case = do.call(cbind, lapply(model.GLMnet.valid.pred, function(x) x$Case))
model.GLMnet.valid.pred.score = apply(model.GLMnet.valid.pred.case, 1, median)

In [8]:
test.ifo$model.GLMnet.valid.pred.score = model.GLMnet.valid.pred.score

In [9]:
test.ifo

         Group  score     model.GLMnet.valid.pred.score
50122R14 Glioma 0.7564621 0.7564621
50124R5  Glioma 0.9349877 0.9349877
51011R3  NBD    0.1498371 0.1498371
60105R10 NBD    0.1009254 0.1009254